- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: start an instance with a public ip address
    amazon.aws.ec2_instance:
      name: "{{ item.name }}"
      key_name: "ansible"
      instance_type: t2.micro
      security_group: default
      region: us-east-1
      aws_access_key: "{{ ec2_access_key }}"
      aws_secret_key: "{{ ec2_secret_key }}"
      network:
        assign_public_ip: true
      image_id: "{{ item.image }}"

    loop:
    - {image: "ami-0866a3c8686eaeeba", name: "ubuntu-1"}
    - {image: "ami-0866a3c8686eaeeba", name: "ubuntu-2"}
    - {image: "ami-06b21ccaeff8cd686", name: "linux"}
