---
- hosts: all
  become: true

  tasks:
    - name: shutdown ubuntu instance only
      ansible.builtin.command: /sbin/shutdown -h now
      when: ansible_facts['os_family'] == "Debian" and ansible_facts['distribution'] == "Ubuntu"
